### ISSUE TITLE
How to train on custom scenes?

### ISSUE THREAD

**Issue by XinYu-Andy** [orig333/Blended-NeRF#2]
Hello, I found that in the code, we need to load a checkpoint to initialize the original scene. I am wondering if I have a custom scene, which means I need to train its NeRF first (instead of directly loading a pretrained checkpoint), how can I modify the configuration file to achieve this?
Thank you!

**Comment by orig333** [comment]
Hi, Thank you for your interest in our work.
 In order to modify a custom scene using our framework you would need to specify the following fields in the configuration file:
1. base_weights - the path to your trained model representing your custom scene. (see base_weights folder).
2. datadir - Path to the input data, depends on its type.(I suggest you that you run download_data.sh script to see how it should look).
3.dataset_type -  the dataset_type - blender/llff/llff and is360Scene=True(real 3D scenes). Currently we support only these 3 types of scenes.
4. box_points_path - After you have all of these you can run the according notebook for your scene to localize a 3 box which will be your region of interest. The path to the box point array should be specify in the field .
5. base_dir - path where all your run logs will be saved.
6. expname - name of the dir which will be saved inside base_dir and will contain the logs for the current run.

Notes:
1. Generally, the documentation of all parameters for the configuration file is located in config_parser function in run_BlenderNeRF.py.
2. You can use the examples provided in the repository to see some use cases. 
3. Our code is based on [NeRF-Pytorch](https://github.com/yenchenlin/nerf-pytorch) so I suggest you will train your scene using this repository.

**Comment by XinYu-Andy** [comment]
> Hi, Thank you for your interest in our work. In order to modify a custom scene using our framework you would need to specify the following fields in the configuration file:
> 
> 1. base_weights - the path to your trained model representing your custom scene. (see base_weights folder).
> 2. datadir - Path to the input data, depends on its type.(I suggest you that you run download_data.sh script to see how it should look).
>    3.dataset_type -  the dataset_type - blender/llff/llff and is360Scene=True(real 3D scenes). Currently we support only these 3 types of scenes.
> 3. box_points_path - After you have all of these you can run the according notebook for your scene to localize a 3 box which will be your region of interest. The path to the box point array should be specify in the field .
> 4. base_dir - path where all your run logs will be saved.
> 5. expname - name of the dir which will be saved inside base_dir and will contain the logs for the current run.
> 
> Notes:
> 
> 1. Generally, the documentation of all parameters for the configuration file is located in config_parser function in run_BlenderNeRF.py.
> 2. You can use the examples provided in the repository to see some use cases.
> 3. Our code is based on [NeRF-Pytorch](https://github.com/yenchenlin/nerf-pytorch) so I suggest you will train your scene using this repository.

Thank you for your response. I'm wondering if I can train a NeRF model, whether it's feed-forward or 360, directly using nerf-pytorch and then load it into your codebase?

**Comment by orig333** [comment]
Yes you can :).
We are using the same architecture as in nerf-pytorch so it should work.
